### ISSUE TITLE
Philosophy of forking

### ISSUE THREAD

**Issue by willcl-ark** [kallerosenbaum/btcphilosophy#13]
I thought this email had some particularly clear points on activation of (soft) forks, and wonder if it could be worth incorporating some of this into some part of the document?

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-March/020127.html

**Comment by kallerosenbaum** [comment]
Definitely! We've planned for an "Upgrading" chapter, thanks for the link!

**Comment by willcl-ark** [comment]
@kallerosenbaum and a followup in the same email thread may contain some more ideas: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-March/020173.html

**Comment by kallerosenbaum** [comment]
The Upgrading chapter is done, but I didn't incorporate the particular emails you linked to. I'll leave this open for another while.

**Comment by kallerosenbaum** [comment]
Moving to leftovers: https://github.com/kallerosenbaum/btcphilosophy/issues/21
