### ISSUE TITLE
Open Source feedback

### ISSUE THREAD

**Issue by adamjonas** [kallerosenbaum/btcphilosophy#14]
> A software project that’s not open source will have a hard time convincing people to use it, since people can’t verify that the software does what it says it does.

Cash app seems to do just fine. This sentence would be more effective if it were more specifically tied back to the section.

> https://www.youtube.com/watch?v=Gs9lJTRZCDc&t=2239s

I'd prefer we use text links like https://btctranscripts.com/greg-maxwell/2015-04-29-gmaxwell-bitcoin-selection-cryptography/#:~:text=art%20of%20selection%20cryptography - (I absolutely love this talk!)

> Bitcoin Core tries really hard to [minimize it’s exposure to third party libraries](https://github.com/bitcoin/bitcoin/blob/master/doc/dependencies.md)

There are some good quotes/tidbits to expand this in https://btctranscripts.com/breaking-bitcoin/2019/bitcoin-build-system/.

Review:
This also a good resource to include: https://github.com/glozow/bitcoin-notes/blob/master/review-checklist.md

The culture shock section:
I'm not a fan of it in its current state. It tells a story of conflict without resolution without the speedy trial and AJ/Achow implementation bits.

> Since Bitcoin is permissionless, it means anyone is allowed to voice their opinions.

This should be tied back to the adversarial thinking section. When everyone has a say, how do you know when/how to weight opinions.

**Comment by kallerosenbaum** [comment]
Thanks @adamjonas, you have some good points.

> I'd prefer we use text links

Yes, I should point to the transcript (which in turn contains a video link). This should keep everyone happy. (And yes, it's a fantastic talk)

> It tells a story of conflict without resolution without the speedy trial and AJ/Achow implementation bits.

Yeah, I should at least mention how it got resolved, but the full story will be told in the upcoming chapter on upgrades.

**Comment by adamjonas** [comment]
What about open-source funding?

**Comment by kallerosenbaum** [comment]
Oh, forgot about that. Will add that too.

**Comment by kallerosenbaum** [comment]
> This sentence would be more effective if it were more specifically tied back to the section.

Easy fix! Removed sentence, which didn't really make sense. It's better without it.

> I'd prefer we use text links

Fixed.

> There are some good quotes/tidbits to expand this in https://btctranscripts.com/breaking-bitcoin/2019/bitcoin-build-system/.

Carl Dong's talk on Guix is fantastic. I added that to "Trustlessness" where we discuss that topic. That chapter was a bit short anyway and would benefit from more content.

> This also a good resource to include: https://github.com/glozow/bitcoin-notes/blob/master/review-checklist.md

Yes, added.

> It tells a story of conflict without resolution without the speedy trial 

Added briefly how the taproot stalling got resolved, and that there's more in the Upgrading chapter.

> This should be tied back to the adversarial thinking section. When everyone has a say, how do you know when/how to weight opinions.

I don't get this. If you think it's important, maybe you could clarify this? Why adversarial thinking? Ignoring this for now.

> What about funding for open-source development?

Added a section "Funding"

**Comment by adamjonas** [comment]
> Since Bitcoin is permissionless, it means anyone is allowed to voice their opinions.

This means that it is easy for one person or a small group to slow down progress. There are some explicit tactics from the field manual in the adversarial thinking section that describe this. And so, if everyone's opinion counts than the process is easy to DoS.

**Comment by kallerosenbaum** [comment]
@adamjonas thanks for that last comment. Fixed.
