### ISSUE TITLE
Trustlessness feedback

### ISSUE THREAD

**Issue by stickies-v** [kallerosenbaum/btcphilosophy#15]
Even though it is touched on in other topics too, I think it might be useful to start with an introduction on why trustlessness is an important topic. In centralized systems, we can rely on a central actor's reputation that they've taken care of security (or roll back in case of issues) and on the legal system to enforce violations, both of which are problematic in pseudonymous decentralized systems. We can't have recourse so we really can't have trust. (And according to the whitepaper, the lack of recourse is a feature, not a bug)

> Bitcoin is trustless, but you still have to trust your software and hardware to some degree.

I think this is a good place to expand on two topics: 1) decoupling of the Bitcoin protocol from real world interactions, and 2) the trustlessness choice each user has (and its implications).

1) As you already mention earlier, the Bitcoin protocol is trustless. To my understanding, this is absolute (but I may miss some nuance). The trustlessness starts to degrade wherever we introduce the real world interactions that are necessary to use Bitcoin in a practical manner, but since they're decoupled from the protocol, they can always be improved going forward. (It's not because they're decoupled that fatal flaws in some interactions can't be fatal for the network because of reputation issues, of course).

2) User choice. There is typically a trade-off between trustlessness and convenience, and not only is it up to the user to choose their preference on the spectrum, they can also change their mind over time since it is decoupled from the protocol. The user who wishes to remove all trust could _theoretically_ do so by building their entire network and hardware stack, of course that would (currently) not be practically feasible.
This selfish choice also has network benefits in that it lowers the switching cost for users. The fact that there is a possibility for users to use Bitcoin over other networks than the internet automatically reduces the extent to which ISPs misbehave, since the further they go the more users will just switch, so it keeps them a bit more honest (the more the easier it becomes to switch). Same story applies to e.g. Bitcoin Core (or other) development, hardware, ... The mere _having_ of alternatives is already a positive force for the trustlessness of the network.

> Bitcoin Core might have sneaked in code that will send your private keys to some bad actor.

nit: devs would have sneaked in code

**Comment by kallerosenbaum** [comment]
Thanks for your comments.

> start with an introduction on why trustlessness is an important topic

Good point! Fixed.

>  The trustlessness starts to degrade wherever we introduce the real world interactions

I think this is pretty much covered. Especially since I fixed the next point.

> User choice

Added a section about this towards the end. But I left "This selfish choice also has network benefits in that it lowers the switching cost for users..." out and put it in a leftovers issue #21 .
