### ISSUE TITLE
open source notes

### ISSUE THREAD

**Issue by adamjonas** [kallerosenbaum/btcphilosophy#18]
> The [coredev.tech](https://coredev.tech/) he mentions is an initiative by developers to meet in person to write and review code together, but it seems to be discontinued at this point.

It's still active. It's just that site isn't maintained. There was one in October '21 and another in March '22.

> Seasoned Bitcoin Core developers might appear very hard-headed for this reason, and it’s usually warranted.

There have been a lot of references to upgrading sprinkled throughout what I've read so far. I think it might make sense to move that chapter up. While it hasn't been written, emphasizing the reason for the conservative nature of bitcoin protocol development should be emphasized and feel like it would good to understand when encountering the adversarial and open source chapters.

**Comment by kallerosenbaum** [comment]
Thanks for your comments. Fixed and closed. Feel free to reopen if you disagree.
