### ISSUE TITLE
Security Oriented Software Section

### ISSUE THREAD

**Issue by jarolrod** [kallerosenbaum/btcphilosophy#25]
in the `opensource.adoc` we have sections that aren't finished, like:
- Verfication/Trust
- Reproducible/Deterministic Builds
- Security vs Features

There is also a `Libraries` sections that feels a bit out of place.

We should move the Libraries section and expand on the unfinished topics in a new chapter which can be titled something like `Security Oriented Software`. Here we expand upon the maxims of bitcoin as open-source security-oriented software that guide the need for things like reproducible builds. Also, why these ideals make it so that we want as few library dependencies as possible, and how they guide the choice for what dependencies we want to include.

**Comment by kallerosenbaum** [comment]
> we have sections that aren't finished

(Oh, now I see what you said on the review meeting.) These were just WIP comments that should not be part of the chapter. I use comments like these to organize my thoughts while working. They are not included in the build output, and should be deleted when the dust settles. Most of it is also handled elsewhere in the book.

I'll think about the Libraries thing though. I do think i fits in this chapter, but maybe we can move/rearrange it within the chapter?

**Comment by kallerosenbaum** [comment]
I decided to keep the Libraries section where it is, but rename it to "Selection cryptography", Done in https://github.com/kallerosenbaum/btcphilosophy/commit/90cd36f693ca36860917d92647637b241a014692
