### ISSUE TITLE
adversarial-thinking thoughts

### ISSUE THREAD

**Issue by adamjonas** [kallerosenbaum/btcphilosophy#5]
I love what you have so far.

I think something for the intro could be something about bitcoin being the biggest honeypot on the planet.

If bitcoin was broken, we would find out quickly (see 0.8 BDB to LevelDB hardfork).

And if some underlying crypto was broken we'd find out as well (maybe add an aside on post-quantum).

And for fun throw in the Peter Todd [piñatas](https://bitcointalk.org/index.php?topic=293382.0).

**Comment by adamjonas** [comment]
"After all, Bitcoin is the greatest honey pot in the world" This is a great point, but maybe needs another sentence (or even half sentence) to explain why that is true.

A suggested edit:
"But as the quote also mentions, the Sybil attack is not effective on the Bitcoin network, because you’re not in any way voting with nodes or entities, but with computing power, but it can help carrying out other attacks." -> "As the quote also mentions, the Sybil attack is not effective on the Bitcoin network because there is no voting with nodes or entities, but with computing power. However, this flat structure leaves the system susceptible to carrying out other attacks."

**Comment by kallerosenbaum** [comment]
Closing and moving leftovers to issue https://github.com/kallerosenbaum/btcphilosophy/issues/21.
