### ISSUE TITLE
finitesupply thoughts

### ISSUE THREAD

**Issue by adamjonas** [kallerosenbaum/btcphilosophy#6]
@linnearosenbaum I like what you have so far but I think this section could be bigger. In the end, this is all code but there are additional layers to this. Like how there are things that are sacrosanct like the finite supply but _could_ be changed. So maybe this part could expand to talk about the developer's relationship with the community. The role of activation and historically how big decisions have been decided (i.e. satoshi, to a small group, to wearing hats). A takeaway from your finite supply write-up could be about the meta idea of the reliability/soundness of the protocol. Money shouldn't change on you and you shouldn't be coerced to upgrade. Bitcoin isn't about moving fast and breaking things (see adversarial thinking section).

Maybe there is something to work in about the layers security model - I like the visualization of [this article](https://insights.deribit.com/market-research/the-onion-model-of-blockchain-security-part-1/) but I know [Lopp has some good stuff](https://www.coindesk.com/markets/2016/11/13/bitcoins-security-model-a-deep-dive/) on this too.

**Comment by glozow** [comment]
I was confused about what the purpose of the finite supply section was (I think because I associate it with the "number go up" school of thinking that we'd probably want to avoid here). But this makes sense to me as a base-layer example of how software development is _very_ different when you're trying to build a money.

**Comment by adamjonas** [comment]
I'm not sure Pieter's `However` quote quite works. Maybe adding a little more context would help, for example, "People say the total will be 21000000 BTC... however, either due to an oversight or intentionally, the coins created in the genesis block cannot be spent. This leaves us with 20999949.9769 BTC…​ however …​ however …"

I'd like to see this connect more with upgrading and the difficulty of making changes to consensus but then going a step further and talk about the difficulty of changing a sacrosanct part of bitcoin. This could even be generalized into the POS/POW discussion. These 30 devs could just change the code! (see https://github.com/bitcoin/bitcoin/pull/24731) This leads to a discussion about what makes bitcoin special and ... bitcoin? Is bitcoin the same without 21M? There might be a Ship of Theseus reference as we talk about changing and adapting as it evolves (see https://medium.com/@BrandonQuittem/bitcoin-is-a-decentralized-organism-mycelium-part-1-3-6ec58cdcfaa6)

**Comment by kallerosenbaum** [comment]
The chapter has been rewritten to a degree. I think most of what's suggested here is addressed in other chapters. I've moved items that I agree with and I haven't handled to a "leftovers" issue #21.

> Like how there are things that are sacrosanct like the finite supply but could be changed

I think this was already addressed in this chapter, but it's possibly clearer now

>  talk about the developer's relationship with the community

Addressed in Open Source

> I'm not sure Pieter's However quote quite work

Fixed

> The role of activation and historically how big decisions have been decided (i.e. satoshi, to a small group, to wearing hats)

Addressed in Open Source, Upgrading, and When shit hits the fan

>  A takeaway from your finite supply write-up could ...

Mostly not fixed. Yeah, this could be addressed better. Adding to leftovers issue https://github.com/kallerosenbaum/btcphilosophy/issues/21.

> Maybe there is something to work in about the layers security model ...

Not sure this works in this chapter. 

> I'd like to see this connect more with upgrading and the difficulty of making changes to consensus but then going a step further and talk about the difficulty of changing a sacrosanct part of bitcoin

I think this was already addressed in this chapter, but it's possibly clearer now

> This could even be generalized into the POS/POW discussion.

Maybe not in this chapter. Also, I want to refrain from opening the POS can of worms.

> Is bitcoin the same without 21M? There might be a Ship of Theseus reference ...

This would be nice, but not done. Moving to leftovers issue https://github.com/kallerosenbaum/btcphilosophy/issues/21.
