### ISSUE TITLE
include section on "permission-less"

### ISSUE THREAD

**Issue by josibake** [kallerosenbaum/btcphilosophy#7]
While it appears to be mentioned in the "Miner decentralization" section (w.r.t censorship resistance), I believe this topic requires its own section. Any person should be able to join the network and transact without being banned or censored and the barrier to using Bitcoin should be kept as low as possible. As developers, this philosophical belief motivates us to ensure that:

* we keep the barrier to entry for running a node as low as possible (resource minimization, good UX)
* favor solutions that enhance privacy
* keep up-to-date and correct translations for Bitcoin Core
* ensure that features are not introduced that favor the laws and regulations of one particular jurisdiction over another
* ensure the p2p network is resilient against preventing nodes from specific geographic regions from joining
* etc, etc

These are just a few ideas off the top of my head, happy to discuss more!

**Comment by kallerosenbaum** [comment]
That's a great point. It's a very important aspect of Bitcoin that somehow escaped us. In our original outline we had a chapter on censorship resistance, but that topic is pretty much covered by the decentralization chapter. I was thinking this morning about replacing the CR chapter with something else, and here's probably the answer. Thanks.

**Comment by kallerosenbaum** [comment]
Or, as you suggest, add a section in the decentralization chapter. If I get a lot of content on the subject, I'll probably opt for a separate chapter.

**Comment by glozow** [comment]
Strongly agree.

> favor solutions that enhance privacy

I think this should be much much stronger. Privacy is the default setting, not an option. Privacy is as good as your weakest link, extremely relevant to our security requirements (i.e. censorship resistance) and it can't be optional.

There's a good tweet thread by Matthew Green on Apple's treatment of privacy. imo his main thesis is that requiring users to manually opt out of privacy invasion and coupling it with a functionality handicap, is really no privacy at all https://twitter.com/matthew_d_green/status/1494297436399058947?s=20&t=w0n-OshMwUAwRRYb9qKDkQ

**Comment by kallerosenbaum** [comment]
@glozow thanks. Do you think that the [privacy chapter](https://rosenbaum.se/btcphil/#privacy) is too vague on this, and that I should put more emphasis on the importance of privacy?

**Comment by kallerosenbaum** [comment]
Many of the comments in this issue have now been handled in the [Neutrality section of Decentralization](https://rosenbaum.se/btcphil/#_neutrality) chapter and new [Permissionless development section of Open Source](https://rosenbaum.se/btcphil/#_permissionless_development) chapter.

**Comment by kallerosenbaum** [comment]
While I didn't cover all your comments on this, I think I've found a reasonable level. We can't be too detailed, or the project would swell too big. Closing, but feel free to reopen if you disagree.
